### ISSUE TITLE
failing with AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by bergerx** [pravishj/esb-smart-meter-integration#4]
using latests commit in this repo through HACS: https://github.com/pravishj/esb-smart-meter-integration/commit/960b9e85d487041b139604c4cc3e9aeaf9ef09ac

I have HA running in a docker.

HA version: 
* Core 2024.12.3
* Frontend 20241127.8

```
2024-12-24 21:52:28.878 ERROR (MainThread) [homeassistant.components.sensor] esb_smart_meter: Error on device update!
Traceback (most recent call last):
  File "/config/custom_components/esb_smart_meter/sensor.py", line 165, in fetch
    self._cached_data = await self._esb_api.fetch()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/esb_smart_meter/sensor.py", line 256, in fetch
    session = await self._hass.async_add_executor_job(self.__login)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/esb_smart_meter/sensor.py", line 227, in __login
    state = form.find('input', {'name': 'state'})['value'],
            ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 737, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/config/custom_components/esb_smart_meter/sensor.py", line 79, in async_update
    self._state = self._get_data(esb_data=await self._esb_api.fetch())
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/esb_smart_meter/sensor.py", line 168, in fetch
    LOGGER.error(translation.get_translation(self._hass, 'error_fetching_data').format(error=err))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.helpers.translation' has no attribute 'get_translation'

```

**Comment by pravishj** [comment]
@bergerx, I have just started working only today. 
I know the problem ESB has changed the login page and method hence this causing an issue. I can fix this but there is another problem as ESB is using CAPTCHA so I am trying out.

**Comment by bergerx** [comment]
Ah i thought you addressed the issues after seeing this comment: https://github.com/RobinJ1995/home-assistant-esb-smart-meter-integration/pull/5#issue-2756971695

**Comment by piotrasd** [comment]
just installed and realise about issue, hope you can get fix soon :) thanks for support

**Comment by bergerx** [comment]
Hey, did you see https://github.com/badger707/esb-smart-meter-reading-automation/commit/078b24ddc81bb01e8122e624032b04fd3b66cfd3

**Comment by piotrasd** [comment]
any update ??

**Comment by bergerx** [comment]
Multiple people verified its working successfully in https://github.com/badger707/esb-smart-meter-reading-automation/issues/8

If you are asking if I'm doing any on this, no, but i believe your question was rather to @pravishj .

**Comment by piotrasd** [comment]
yes

**Comment by pravishj** [comment]
@piotrasd and @bergerx, yes saw this now.I have asked badger707 if he wants to integrate my work to his as he has done 90% of the work I have worked the HACS requirements. 

I will try to understand what he has done and try to incorporate it.
